import { z } from "zod";

const CatalogIdentifierSchema = z.object({
  type: z.enum(["GTIN", "EAN", "UPC", "MPN", "SKU"]),
  value: z.string().min(1),
  merchantId: z.string().min(1).optional(),
  fixtureOnly: z.boolean().default(false),
});

export const CatalogProductSchema = z.object({
  id: z.string().min(1),
  brand: z.string().min(1),
  model: z.string().min(1),
  category: z.string().min(1),
  attributes: z.record(z.string(), z.string()),
  identifiers: z.array(CatalogIdentifierSchema),
  aliases: z.array(z.string().min(1)),
});
export type CatalogProduct = z.infer<typeof CatalogProductSchema>;

const product = (value: CatalogProduct) => CatalogProductSchema.parse(value);

export const demoCatalog: readonly CatalogProduct[] = [
  product({
    id: "nike-dunk-low-retro-white-black",
    brand: "Nike",
    model: "Dunk Low",
    category: "shoes",
    attributes: { audience: "adult", silhouette: "low", colorway: "white-black" },
    identifiers: [
      { type: "MPN", value: "DD1391-100", fixtureOnly: false },
      { type: "SKU", value: "WAW-DUNK-PANDA", merchantId: "merchant-warsaw-sneakers", fixtureOnly: true },
    ],
    aliases: ["nike dunk low retro white black", "nike dunk low panda", "dunk low black white"],
  }),
  product({
    id: "nike-dunk-high-demo",
    brand: "Nike",
    model: "Dunk High",
    category: "shoes",
    attributes: { audience: "adult", silhouette: "high", colorway: "white-black" },
    identifiers: [{ type: "MPN", value: "FIXTURE-DUNK-HIGH", fixtureOnly: true }],
    aliases: ["nike dunk high", "dunk high white black"],
  }),
  product({
    id: "nike-sb-dunk-low-demo",
    brand: "Nike",
    model: "SB Dunk Low",
    category: "shoes",
    attributes: { audience: "adult", silhouette: "low", line: "sb" },
    identifiers: [{ type: "MPN", value: "FIXTURE-SB-DUNK", fixtureOnly: true }],
    aliases: ["nike sb dunk low", "sb dunk low"],
  }),
  product({
    id: "nike-dunk-low-gs-demo",
    brand: "Nike",
    model: "Dunk Low GS",
    category: "shoes",
    attributes: { audience: "grade-school", silhouette: "low" },
    identifiers: [{ type: "MPN", value: "FIXTURE-DUNK-GS", fixtureOnly: true }],
    aliases: ["nike dunk low gs", "dunk low kids", "dunk low grade school"],
  }),
  product({
    id: "nike-dunk-low-next-nature-demo",
    brand: "Nike",
    model: "Dunk Low Next Nature",
    category: "shoes",
    attributes: { audience: "adult", silhouette: "low", line: "next-nature" },
    identifiers: [{ type: "MPN", value: "FIXTURE-DUNK-NN", fixtureOnly: true }],
    aliases: ["nike dunk low next nature", "dunk low nn"],
  }),
  product({
    id: "sony-wh-1000xm5-black-demo",
    brand: "Sony",
    model: "WH-1000XM5",
    category: "electronics",
    attributes: { productType: "headphones", fit: "over-ear", color: "black", connectivity: "wireless" },
    identifiers: [{ type: "MPN", value: "FIXTURE-SONY-WH1000XM5-B", fixtureOnly: true }],
    aliases: ["sony wh-1000xm5 black", "sony xm5 headphones black", "wh1000xm5 wireless headphones"],
  }),
  product({
    id: "sony-wh-1000xm4-black-demo",
    brand: "Sony",
    model: "WH-1000XM4",
    category: "electronics",
    attributes: { productType: "headphones", fit: "over-ear", color: "black", connectivity: "wireless" },
    identifiers: [{ type: "MPN", value: "FIXTURE-SONY-WH1000XM4-B", fixtureOnly: true }],
    aliases: ["sony wh-1000xm4 black", "sony xm4 headphones black", "wh1000xm4 wireless headphones"],
  }),
  product({
    id: "nintendo-switch-oled-white-demo",
    brand: "Nintendo",
    model: "Switch OLED",
    category: "gaming",
    attributes: { productType: "console", edition: "oled", color: "white", region: "europe" },
    identifiers: [{ type: "MPN", value: "FIXTURE-SWITCH-OLED-WHITE", fixtureOnly: true }],
    aliases: ["nintendo switch oled white", "switch oled white joy-con", "nintendo oled console white"],
  }),
  product({
    id: "nintendo-switch-standard-neon-demo",
    brand: "Nintendo",
    model: "Switch",
    category: "gaming",
    attributes: { productType: "console", edition: "standard", color: "neon", region: "europe" },
    identifiers: [{ type: "MPN", value: "FIXTURE-SWITCH-STANDARD-NEON", fixtureOnly: true }],
    aliases: ["nintendo switch standard neon", "switch neon red blue", "nintendo switch v2 neon"],
  }),
  product({
    id: "dyson-v15-detect-demo",
    brand: "Dyson",
    model: "V15 Detect",
    category: "home-appliances",
    attributes: { productType: "vacuum-cleaner", form: "cordless-stick", edition: "detect", condition: "new" },
    identifiers: [{ type: "MPN", value: "FIXTURE-DYSON-V15-DETECT", fixtureOnly: true }],
    aliases: ["dyson v15 detect", "v15 detect cordless vacuum", "dyson detect v15 cleaner"],
  }),
  product({
    id: "dyson-v12-detect-slim-demo",
    brand: "Dyson",
    model: "V12 Detect Slim",
    category: "home-appliances",
    attributes: { productType: "vacuum-cleaner", form: "cordless-stick", edition: "detect-slim", condition: "new" },
    identifiers: [{ type: "MPN", value: "FIXTURE-DYSON-V12-DETECT-SLIM", fixtureOnly: true }],
    aliases: ["dyson v12 detect slim", "v12 detect slim cordless vacuum", "dyson slim v12 cleaner"],
  }),
  product({
    id: "sage-barista-express-demo",
    brand: "Sage",
    model: "Barista Express",
    category: "kitchen-appliances",
    attributes: { productType: "espresso-machine", grinder: "integrated", finish: "stainless-steel", market: "europe" },
    identifiers: [{ type: "MPN", value: "FIXTURE-SAGE-BARISTA-EXPRESS", fixtureOnly: true }],
    aliases: ["sage barista express", "barista express coffee machine", "sage express espresso machine"],
  }),
  product({
    id: "sage-barista-pro-demo",
    brand: "Sage",
    model: "Barista Pro",
    category: "kitchen-appliances",
    attributes: { productType: "espresso-machine", grinder: "integrated", finish: "stainless-steel", market: "europe" },
    identifiers: [{ type: "MPN", value: "FIXTURE-SAGE-BARISTA-PRO", fixtureOnly: true }],
    aliases: ["sage barista pro", "barista pro coffee machine", "sage pro espresso machine"],
  }),
  product({
    id: "garmin-forerunner-265-black-demo",
    brand: "Garmin",
    model: "Forerunner 265",
    category: "sports-tech",
    attributes: { productType: "gps-running-watch", caseSize: "46mm", color: "black", display: "amoled" },
    identifiers: [{ type: "MPN", value: "FIXTURE-GARMIN-FR265-B", fixtureOnly: true }],
    aliases: ["garmin forerunner 265 black", "garmin fr265 black", "forerunner 265 running watch"],
  }),
  product({
    id: "garmin-forerunner-265s-black-demo",
    brand: "Garmin",
    model: "Forerunner 265S",
    category: "sports-tech",
    attributes: { productType: "gps-running-watch", caseSize: "42mm", color: "black", display: "amoled" },
    identifiers: [{ type: "MPN", value: "FIXTURE-GARMIN-FR265S-B", fixtureOnly: true }],
    aliases: ["garmin forerunner 265s black", "garmin fr265s black", "forerunner 265s running watch"],
  }),
  product({
    id: "lego-technic-mercedes-f1-demo",
    brand: "LEGO",
    model: "Technic Mercedes-AMG F1 W14",
    category: "toys",
    attributes: { productType: "construction-set", theme: "technic", vehicle: "mercedes-amg-f1-w14", ageRange: "18+" },
    identifiers: [{ type: "MPN", value: "FIXTURE-LEGO-42171", fixtureOnly: true }],
    aliases: ["lego technic mercedes-amg f1 w14", "lego mercedes f1 42171", "technic mercedes w14"],
  }),
  product({
    id: "lego-technic-mclaren-f1-demo",
    brand: "LEGO",
    model: "Technic McLaren Formula 1",
    category: "toys",
    attributes: { productType: "construction-set", theme: "technic", vehicle: "mclaren-formula-1", ageRange: "18+" },
    identifiers: [{ type: "MPN", value: "FIXTURE-LEGO-42141", fixtureOnly: true }],
    aliases: ["lego technic mclaren formula 1", "lego mclaren f1 42141", "technic mclaren formula one"],
  }),
];

export const disclosedSeededMappings = demoCatalog.flatMap((entry) => entry.aliases.map((alias) => ({
  alias,
  canonicalProductId: entry.id,
  provenance: "Disclosed hackathon demo alias; not an independently verified merchant mapping.",
})));
